ARRAYSPECREPO = https://github.com/akvashi24/cs4500-A1-part2
ARRAYSPECHASH = 8ed2386acc995e30d77f2a4799440f5662ee4541
QUEUESPECREPO = https://github.com/dxandbatista/A1-pt2
QUEUESPECHASH = 846731936746ab015534c4b1888fb7722a5a45a9
MAPSPECREPO = https://github.com/Xiaocheng-Zhang/part2
MAPSPECHASH = 24bbdd8d73a1c483777fbc7afcc9b9f3e7d0859b

run: 
	- make testArray
	- make testQueue
	- make testMap

testArray:
	

testQueue:

testMap: