ARRAYSPECREPO = https://github.com/akvashi24/cs4500-A1-part2
ARRAYSPECHASH = 8ed2386acc995e30d77f2a4799440f5662ee4541
QUEUESPECREPO = https://github.com/dxandbatista/A1-pt2
QUEUESPECHASH = 846731936746ab015534c4b1888fb7722a5a45a9
MAPSPECREPO = https://github.com/Xiaocheng-Zhang/part2
MAPSPECHASH = dc8d95527aaa6f942160d3b94c1794acf64682cf

run: 
	- make testArray
	- make testQueue
	- make testMap

testArray:
	g++ test-array.cpp -o array.out -Wall
	./array.out


testQueue:
	g++ test-queue.cpp -o queue.out -Wall   
	./queue.out

testMap:
	g++ test-map.cpp -o map.out -Wall   
	./map.out